### ISSUE TITLE
Not working last step plzz fiz it 

### ISSUE THREAD

**Issue by CodeWithAdityaKumar** [SociallyIneptWeeb/AICoverGen#107]
Error:- 
![Screenshot_2024-02-09-17-28-19-63_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/SociallyIneptWeeb/AICoverGen/assets/127035083/54e9decb-3d2f-4e08-a43b-73b925a2aa18)

Traceback (most recent call last):
  File "/content/AICoverGen/src/main.py", line 11, in <module>
    import gradio as gr
  File "/usr/local/lib/python3.10/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/annotated_image.py", line 8, in <module>
    from gradio_client.documentation import document, set_documentation_group
ImportError: cannot import name 'set_documentation_group' from 'gradio_client.documentation' (/usr/local/lib/python3.10/dist-packages/gradio_client/documentation.py)
1

**Comment by 5Nvite** [comment]
Fix with pip install gradio_client==0.2.10
