### ISSUE TITLE
WinError 267

### ISSUE THREAD

**Issue by K0shachiyamyatA** [SociallyIneptWeeb/AICoverGen#115]
i chose my voice model and a local song file, pressed the generate button and got this:

```
Traceback (most recent call last):
  File "H:\pythontrash\cover\src\main.py", line 291, in song_cover_pipeline
    voice_change(voice_model, main_vocals_dereverb_path, ai_vocals_path, pitch_change, f0_method, index_rate, filter_radius, rms_mix_rate, protect, crepe_hop_length, is_webui)
  File "H:\pythontrash\cover\src\main.py", line 194, in voice_change
    rvc_model_path, rvc_index_path = get_rvc_model(voice_model, is_webui)
  File "H:\pythontrash\cover\src\main.py", line 91, in get_rvc_model
    for file in os.listdir(model_dir):
NotADirectoryError: [WinError 267] Неверно задано имя папки: 'H:\\pythontrash\\cover\\rvc_models\\Melantha.pth'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1392, in process_api
    result = await self.call_function(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1097, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
  File "H:\pythontrash\cover\src\main.py", line 316, in song_cover_pipeline
    raise_exception(str(e), is_webui)
  File "H:\pythontrash\cover\src\main.py", line 83, in raise_exception
    raise gr.Error(error_msg)
gradio.exceptions.Error: "[WinError 267] Неверно задано имя папки: 'H:\\\\pythontrash\\\\cover\\\\rvc_models\\\\Melantha.pth'"
```

**Comment by evrimkilic007** [comment]
Same issue here, has no fix been found?
