### ISSUE TITLE
ERROR: Failed building wheel for fairseq

### ISSUE THREAD

**Issue by Crazy-Hunt** [SociallyIneptWeeb/AICoverGen#132]
Got this error trying to install fairseq using `pip install -r requirements.txt`
I tried:
`pip install fairseq==0.12.2`
as well as:
`git clone https://github.com/pytorch/fairseq`
`cd fairseq`
`pip install --editable ./`
which i found on the fairseq github page: https://github.com/facebookresearch/fairseq
I'm on windows 10

Last bit output:
```cpython-310\fairseq\config\model\wav2vec2
      running build_ext
      building 'fairseq.libbleu' extension
      Traceback (most recent call last):
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\Alex\AppData\Local\Temp\pip-build-env-a4m2bus9\overlay\Lib\site-packages\setuptools\build_meta.py", line 415, in build_wheel
          return self._build_with_temp_dir(
        File "C:\Users\Alex\AppData\Local\Temp\pip-build-env-a4m2bus9\overlay\Lib\site-packages\setuptools\build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\Alex\AppData\Local\Temp\pip-build-env-a4m2bus9\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 270, in <module>
        File "<string>", line 178, in do_setup
        File "C:\Users\Alex\AppData\Local\Temp\pip-build-env-a4m2bus9\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Alex\AppData\Local\Temp\pip-build-env-a4m2bus9\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
          return run_commands(dist)
        File "C:\Users\Alex\AppData\Local\Temp\pip-build-env-a4m2bus9\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
          dist.run_commands()
        File "C:\Users\Alex\AppData\Local\Temp\pip-build-env-a4m2bus9\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\Alex\AppData\Local\Temp\pip-build-env-a4m2bus9\overlay\Lib\site-packages\setuptools\dist.py", line 976, in run_command
          super().run_command(command)
        File "C:\Users\Alex\AppData\Local\Temp\pip-build-env-a4m2bus9\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Alex\AppData\Local\Temp\pip-build-env-a4m2bus9\overlay\Lib\site-packages\setuptools\command\bdist_wheel.py", line 373, in run
          self.run_command("build")
        File "C:\Users\Alex\AppData\Local\Temp\pip-build-env-a4m2bus9\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Alex\AppData\Local\Temp\pip-build-env-a4m2bus9\overlay\Lib\site-packages\setuptools\dist.py", line 976, in run_command
          super().run_command(command)
        File "C:\Users\Alex\AppData\Local\Temp\pip-build-env-a4m2bus9\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Alex\AppData\Local\Temp\pip-build-env-a4m2bus9\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "C:\Users\Alex\AppData\Local\Temp\pip-build-env-a4m2bus9\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Alex\AppData\Local\Temp\pip-build-env-a4m2bus9\overlay\Lib\site-packages\setuptools\dist.py", line 976, in run_command
          super().run_command(command)
        File "C:\Users\Alex\AppData\Local\Temp\pip-build-env-a4m2bus9\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Alex\AppData\Local\Temp\pip-build-env-a4m2bus9\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 93, in run
          _build_ext.run(self)
        File "C:\Users\Alex\AppData\Local\Temp\pip-build-env-a4m2bus9\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 359, in run
          self.build_extensions()
        File "C:\Users\Alex\AppData\Local\Temp\pip-build-env-a4m2bus9\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 479, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\Alex\AppData\Local\Temp\pip-build-env-a4m2bus9\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 505, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\Users\Alex\AppData\Local\Temp\pip-build-env-a4m2bus9\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 254, in build_extension
          _build_ext.build_extension(self, ext)
        File "C:\Users\Alex\AppData\Local\Temp\pip-build-env-a4m2bus9\overlay\Lib\site-packages\Cython\Distutils\build_ext.py", line 135, in build_extension
          super(build_ext, self).build_extension(ext)
        File "C:\Users\Alex\AppData\Local\Temp\pip-build-env-a4m2bus9\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 560, in build_extension
          objects = self.compiler.compile(
        File "C:\Users\Alex\AppData\Local\Temp\pip-build-env-a4m2bus9\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 343, in compile
          self.initialize()
        File "C:\Users\Alex\AppData\Local\Temp\pip-build-env-a4m2bus9\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 253, in initialize
          vc_env = _get_vc_env(plat_spec)
        File "C:\Users\Alex\AppData\Local\Temp\pip-build-env-a4m2bus9\overlay\Lib\site-packages\setuptools\msvc.py", line 232, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
        File "C:\Users\Alex\AppData\Local\Temp\pip-build-env-a4m2bus9\overlay\Lib\site-packages\setuptools\msvc.py", line 187, in _msvc14_get_vc_env
          vcvarsall, vcruntime = _msvc14_find_vcvarsall(plat_spec)
        File "C:\Users\Alex\AppData\Local\Temp\pip-build-env-a4m2bus9\overlay\Lib\site-packages\setuptools\msvc.py", line 131, in _msvc14_find_vcvarsall
          _, best_dir = _msvc14_find_vc2017()
        File "C:\Users\Alex\AppData\Local\Temp\pip-build-env-a4m2bus9\overlay\Lib\site-packages\setuptools\msvc.py", line 99, in _msvc14_find_vc2017
          subprocess.check_output([
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 421, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\site-packages\run\__init__.py", line 145, in __new__
          process = cls.create_process(command, stdin, cwd=cwd, env=env, shell=shell)
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\site-packages\run\__init__.py", line 121, in create_process
          shlex.split(command),
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\shlex.py", line 315, in split
          return list(lex)
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\shlex.py", line 300, in __next__
          token = self.get_token()
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\shlex.py", line 109, in get_token
          raw = self.read_token()
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\shlex.py", line 140, in read_token
          nextchar = self.instream.read(1)
      AttributeError: 'list' object has no attribute 'read'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fairseq
Failed to build fairseq
ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects```

The full output:
[Error.txt](https://github.com/user-attachments/files/15904224/Error.txt)

**Comment by Beterng** [comment]
The issue has been post but need wating host to fix the problem.
https://github.com/facebookresearch/fairseq/issues/5511#issue-2369590999

**Comment by Crazy-Hunt** [comment]
Forgot to come back here to update, i fixed it by following this: https://stackoverflow.com/questions/64261546/how-to-solve-error-microsoft-visual-c-14-0-or-greater-is-required-when-inst
now getting a new error:
ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory
