### ISSUE TITLE
Error build for fairseq==0.12.2 in requirements.txt file.

### ISSUE THREAD

**Issue by Beterng** [SociallyIneptWeeb/AICoverGen#133]
I was instal the fisrt requirements.txt fisrt.
```txt
deemix
fairseq==0.12.2
faiss-cpu==1.7.3
ffmpeg-python>=0.2.0
gradio==3.39.0
lib==4.0.0
librosa==0.9.1
numpy==1.23.5
onnxruntime_gpu
praat-parselmouth>=0.4.2
pedalboard==0.7.7
pydub==0.25.1
pyworld==0.3.4
Requests==2.31.0
scipy==1.11.1
soundfile==0.12.1
--find-links https://download.pytorch.org/whl/torch_stable.html
torch==2.0.1+cu118
torchcrepe==0.0.20
tqdm==4.65.0
yt_dlp==2023.7.6
sox==1.4.1
```
But it was have have this problem:
```
ERROR: Cannot install -r requirements.txt (line 2) and omegaconf==2.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    fairseq 0.12.2 depends on omegaconf<2.1
    hydra-core 1.0.7 depends on omegaconf<2.1 and >=2.0.5

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

So i was add a 1 line in line number 15 like this omegaconf==2.0.6 like this. It was fix the ploblem `conflict is caused` :
```
deemix
fairseq==0.12.2
faiss-cpu==1.7.3
ffmpeg-python>=0.2.0
gradio==3.39.0
lib==4.0.0
librosa==0.9.1
numpy==1.23.5
onnxruntime_gpu

omegaconf==2.0.6

praat-parselmouth>=0.4.2
pedalboard==0.7.7
pydub==0.25.1
pyworld==0.3.4
Requests==2.31.0
scipy==1.11.1
soundfile==0.12.1
--find-links https://download.pytorch.org/whl/torch_stable.html
torch==2.0.1+cu118
torchcrepe==0.0.20
tqdm==4.65.0
yt_dlp==2023.7.6
sox==1.4.1
```

It have a new problem.
```
Collecting fairseq==0.12.2
  Using cached fairseq-0.12.2.tar.gz (9.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: cffi in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from fairseq==0.12.2) (1.16.0)
Requirement already satisfied: cython in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from fairseq==0.12.2) (3.0.10)
Collecting hydra-core<1.1,>=1.0.7 (from fairseq==0.12.2)
  Using cached hydra_core-1.0.7-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: omegaconf<2.1 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages\omegaconf-2.0.6-py3.10.egg (from fairseq==0.12.2) (2.0.6)
Collecting regex (from fairseq==0.12.2)
  Using cached regex-2024.5.15-cp310-cp310-win_amd64.whl.metadata (41 kB)
Collecting sacrebleu>=1.4.12 (from fairseq==0.12.2)
  Using cached sacrebleu-2.4.2-py3-none-any.whl.metadata (58 kB)
Collecting torch (from fairseq==0.12.2)
  Using cached torch-2.3.1-cp310-cp310-win_amd64.whl.metadata (26 kB)
Collecting tqdm (from fairseq==0.12.2)
  Using cached tqdm-4.66.4-py3-none-any.whl.metadata (57 kB)
Collecting bitarray (from fairseq==0.12.2)
  Using cached bitarray-2.9.2-cp310-cp310-win_amd64.whl.metadata (35 kB)
Requirement already satisfied: torchaudio>=0.8.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from fairseq==0.12.2) (2.3.1+cu121)
Collecting numpy (from fairseq==0.12.2)
  Using cached numpy-2.0.0-cp310-cp310-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: antlr4-python3-runtime==4.8 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from hydra-core<1.1,>=1.0.7->fairseq==0.12.2) (4.8)
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2751, in _dep_map
    return self.__dep_map
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2863, in __getattr__
    raise AttributeError(attr)
AttributeError: _Distribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\packaging\requirements.py", line 36, in __init__
    parsed = _parse_requirement(requirement_string)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\packaging\_parser.py", line 62, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\packaging\_parser.py", line 80, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\packaging\_parser.py", line 118, in _parse_requirement_details
    specifier = _parse_specifier(tokenizer)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\packaging\_parser.py", line 214, in _parse_specifier
    parsed_specifiers = _parse_version_many(tokenizer)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\packaging\_parser.py", line 229, in _parse_version_many
    tokenizer.raise_syntax_error(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\packaging\_tokenizer.py", line 167, in raise_syntax_error
    raise ParserSyntaxError(
pip._vendor.packaging._tokenizer.ParserSyntaxError: .* suffix can only be used with `==` or `!=` operators
    PyYAML>=5.1.*
          ~~~~~~^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\cli\base_command.py", line 179, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 427, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 239, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 229, in _get_updated_criteria
    for requirement in self._p.get_dependencies(candidate=candidate):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\provider.py", line 247, in get_dependencies
    return [r for r in candidate.iter_dependencies(with_requires) if r is not None]
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\provider.py", line 247, in <listcomp>
    return [r for r in candidate.iter_dependencies(with_requires) if r is not None]
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 401, in iter_dependencies
    for r in self.dist.iter_dependencies():
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\metadata\pkg_resources.py", line 247, in iter_dependencies
    return self._dist.requires(extras)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2786, in requires
    dm = self._dep_map
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2753, in _dep_map
    self.__dep_map = self._filter_extras(self._build_dep_map())
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2781, in _build_dep_map
    dm.setdefault(extra, []).extend(parse_requirements(reqs))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3135, in __init__
    super().__init__(requirement_string)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\packaging\requirements.py", line 38, in __init__
    raise InvalidRequirement(str(e)) from e
pip._vendor.packaging.requirements.InvalidRequirement: .* suffix can only be used with `==` or `!=` operators
    PyYAML>=5.1.*
          ~~~~~~^
```

is the version or some pip package in your requirements.txt is correct?

**Comment by Beterng** [comment]
Note i have run an other build using command ( Python 3.10.11 ) when omegaconf is not add:
```
py -3.10 -m pip install fairseq
```
and
```
py -3.10 -m pip install fairseq==0.12.2
```

Log:
```
ERROR: Cannot install -r requirements.txt (line 2) and omegaconf==2.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested omegaconf==2.2
    fairseq 0.12.2 depends on omegaconf<2.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**using command ( Python 3.10.11 ) when omegaconf==2.0.6:**
```
py -3.10 -m pip install fairseq
```
and
```
py -3.10 -m pip install fairseq==0.12.2
```

Log
```
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2751, in _dep_map
    return self.__dep_map
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2863, in __getattr__
    raise AttributeError(attr)
AttributeError: _Distribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\packaging\requirements.py", line 36, in __init__
    parsed = _parse_requirement(requirement_string)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\packaging\_parser.py", line 62, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\packaging\_parser.py", line 80, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\packaging\_parser.py", line 118, in _parse_requirement_details
    specifier = _parse_specifier(tokenizer)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\packaging\_parser.py", line 214, in _parse_specifier
    parsed_specifiers = _parse_version_many(tokenizer)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\packaging\_parser.py", line 229, in _parse_version_many
    tokenizer.raise_syntax_error(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\packaging\_tokenizer.py", line 167, in raise_syntax_error
    raise ParserSyntaxError(
pip._vendor.packaging._tokenizer.ParserSyntaxError: .* suffix can only be used with `==` or `!=` operators
    PyYAML>=5.1.*
          ~~~~~~^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\cli\base_command.py", line 179, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 427, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 239, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 229, in _get_updated_criteria
    for requirement in self._p.get_dependencies(candidate=candidate):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\provider.py", line 247, in get_dependencies
    return [r for r in candidate.iter_dependencies(with_requires) if r is not None]
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\provider.py", line 247, in <listcomp>
    return [r for r in candidate.iter_dependencies(with_requires) if r is not None]
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 401, in iter_dependencies
    for r in self.dist.iter_dependencies():
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\metadata\pkg_resources.py", line 247, in iter_dependencies
    return self._dist.requires(extras)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2786, in requires
    dm = self._dep_map
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2753, in _dep_map
    self.__dep_map = self._filter_extras(self._build_dep_map())
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2781, in _build_dep_map
    dm.setdefault(extra, []).extend(parse_requirements(reqs))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3135, in __init__
    super().__init__(requirement_string)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\packaging\requirements.py", line 38, in __init__
    raise InvalidRequirement(str(e)) from e
pip._vendor.packaging.requirements.InvalidRequirement: .* suffix can only be used with `==` or `!=` operators
    PyYAML>=5.1.*
          ~~~~~~^
```

**Comment by Beterng** [comment]
New the issue was found make by omegaconf==2.0.6

**Comment by shaikhalid** [comment]
I think the issue is with pip >=24.1, they have made some changes to the dependency resolver. Try using pip 24.0

**Comment by Beterng** [comment]
Thank you ploblem fixed 🥹
