### ISSUE TITLE
 Error opening '*.webm': Format not recognised.

### ISSUE THREAD

**Issue by igmndez** [SociallyIneptWeeb/AICoverGen#17]
After several tests, I'm always getting the same error when trying to generate (with several audio models and youtube links). During the installation I haven't had any errors, although I haven't managed to activate the AVX2 support from faiss.

OS: win 10
GPU:  Nvidia GeForce RTX 3080

**Startup log**
2023-08-03 22:40:48 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
2023-08-03 22:40:48 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-08-03 22:40:48 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-08-03 22:40:48 | INFO | faiss.loader | Loading faiss.
2023-08-03 22:40:48 | INFO | faiss.loader | Successfully loaded faiss.
Running on local URL:  http://127.0.0.1:7860

**Error Log**
Traceback (most recent call last):
  File "C:\Users\igmnd\.conda\envs\py39\lib\site-packages\librosa\core\audio.py", line 155, in load
    context = sf.SoundFile(path)
  File "C:\Users\igmnd\.conda\envs\py39\lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Users\igmnd\.conda\envs\py39\lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'youtube_video.webm': Format not recognised.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AICoverGen\src\webui.py", line 65, in song_cover_pipeline
    orig_song_path, vocals_path, instrumentals_path, main_vocals_path, backup_vocals_path, main_vocals_dereverb_path = preprocess_song(yt_link, mdx_model_params, song_id, progress)
  File "D:\AICoverGen\src\main.py", line 89, in preprocess_song
    vocals_path, instrumentals_path = run_mdx(mdx_model_params, song_output_dir, os.path.join(mdxnet_models_dir, 'UVR-MDX-NET-Voc_FT.onnx'), orig_song_path, denoise=True, keep_orig=False)
  File "D:\AICoverGen\src\mdx.py", line 257, in run_mdx
    wave, sr = librosa.load(filename, mono=False, sr=44100)
  File "C:\Users\igmnd\.conda\envs\py39\lib\site-packages\librosa\util\decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\igmnd\.conda\envs\py39\lib\site-packages\librosa\core\audio.py", line 174, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "C:\Users\igmnd\.conda\envs\py39\lib\site-packages\librosa\core\audio.py", line 198, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "C:\Users\igmnd\.conda\envs\py39\lib\site-packages\audioread\__init__.py", line 132, in audio_open
    raise NoBackendError()
audioread.exceptions.NoBackendError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\igmnd\.conda\envs\py39\lib\site-packages\gradio\routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\igmnd\.conda\envs\py39\lib\site-packages\gradio\blocks.py", line 1392, in process_api
    result = await self.call_function(
  File "C:\Users\igmnd\.conda\envs\py39\lib\site-packages\gradio\blocks.py", line 1097, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\igmnd\.conda\envs\py39\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\igmnd\.conda\envs\py39\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\igmnd\.conda\envs\py39\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\igmnd\.conda\envs\py39\lib\site-packages\gradio\utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
  File "D:\AICoverGen\src\webui.py", line 99, in song_cover_pipeline
    raise gr.Error(str(e))
gradio.exceptions.Error: ''
2023-08-03 22:41:25 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 500 Internal Server Error"

**Comment by igmndez** [comment]
I just read your post, but I wasn't linking it. Just now I managed to run it without problems in another video.

Thanks for the reply!
