### ISSUE TITLE
Issues on cpu "ValueError"

### ISSUE THREAD

**Issue by codecooker1** [SociallyIneptWeeb/AICoverGen#28]
ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory

Traceback (most recent call last):
  File "/run/media/saminur/none/Coding Bug/Python/pi/RVC/AICoverGen/src/webui.py", line 10, in <module>
    from main import song_cover_pipeline
  File "/run/media/saminur/none/Coding Bug/Python/pi/RVC/AICoverGen/src/main.py", line 16, in <module>
    from rvc import Config, load_hubert, get_vc, rvc_infer
  File "/run/media/saminur/none/Coding Bug/Python/pi/RVC/AICoverGen/src/rvc.py", line 5, in <module>
    from fairseq import checkpoint_utils
  File "/run/media/saminur/none/Coding Bug/Python/lib/python3.11/site-packages/fairseq/__init__.py", line 20, in <module>
    from fairseq.distributed import utils as distributed_utils
  File "/run/media/saminur/none/Coding Bug/Python/lib/python3.11/site-packages/fairseq/distributed/__init__.py", line 7, in <module>
    from .fully_sharded_data_parallel import (
  File "/run/media/saminur/none/Coding Bug/Python/lib/python3.11/site-packages/fairseq/distributed/fully_sharded_data_parallel.py", line 10, in <module>
    from fairseq.dataclass.configs import DistributedTrainingConfig
  File "/run/media/saminur/none/Coding Bug/Python/lib/python3.11/site-packages/fairseq/dataclass/__init__.py", line 6, in <module>
    from .configs import FairseqDataclass
  File "/run/media/saminur/none/Coding Bug/Python/lib/python3.11/site-packages/fairseq/dataclass/configs.py", line 1104, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1223, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1213, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory

**Comment by SociallyIneptWeeb** [comment]
If you do not have an NVIDIA GPU, you can try running it via the google colab. This may not work without one.

**Comment by codecooker1** [comment]
I did a bit of research and found this specific error has nothing to do with GPU.
I'm using python 3.11 on my local machine and fairseq doesn't seem work with this but it works with python 3.10.

### Working with CPU
 I'm trying to run it with cpu instead of gpu. (as I don't have one)
It should have worked with cpu if I just set the device to to torch.device("cpu") instead of torch.device("cuda")
[https://discuss.pytorch.org/t/trying-to-run-cpu-instead-of-cuda/175331/2](url)

and it seems that it's already done in the rvc code: (vc_infer_pipeline.py line:83)
```
    def get_optimal_torch_device(self, index: int = 0) -> torch.device:
        # Get cuda device
        if torch.cuda.is_available():
            return torch.device(
                f"cuda:{index % torch.cuda.device_count()}"
            )  # Very fast
        elif torch.backends.mps.is_available():
            return torch.device("mps")
        # Insert an else here to grab "xla" devices if available. TO DO later. Requires the torch_xla.core.xla_model library
        # Else wise return the "cpu" as a torch device,
        return torch.device("cpu")
```

So, i tried it with the cpu version huggingface space but I get the error that it needs nvidia drivers
```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/user/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/home/user/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/user/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/user/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/user/.local/lib/python3.10/site-packages/gradio/utils.py", line 706, in wrapper
    response = f(*args, **kwargs)
  File "/home/user/app/src/main.py", line 274, in song_cover_pipeline
    raise_exception(str(e), is_webui)
  File "/home/user/app/src/main.py", line 76, in raise_exception
    raise gr.Error(error_msg)
gradio.exceptions.Error: 'Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx'
  ```
```
Traceback (most recent call last):
  File "/home/user/app/src/main.py", line 247, in song_cover_pipeline
    orig_song_path, vocals_path, instrumentals_path, main_vocals_path, backup_vocals_path, main_vocals_dereverb_path = preprocess_song(song_input, mdx_model_params, song_id, is_webui, input_type, progress)
  File "/home/user/app/src/main.py", line 149, in preprocess_song
    vocals_path, instrumentals_path = run_mdx(mdx_model_params, song_output_dir, os.path.join(mdxnet_models_dir, 'UVR-MDX-NET-Voc_FT.onnx'), orig_song_path, denoise=True, keep_orig=keep_orig)
  File "/home/user/app/src/mdx.py", line 241, in run_mdx
    device_properties = torch.cuda.get_device_properties(device)
  File "/home/user/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 395, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "/home/user/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```
Any opinions about what I should do?
The google colab version get blocked and I want to make it as an flask api for my other python project.

**Comment by SociallyIneptWeeb** [comment]
Can you explain what you mean by Google colab version gets blocked? Maybe we can fix that

**Comment by codecooker1** [comment]
The runtime just stops after half minute or so whenever in the webui.
Maybe colab blocks server hosting codes (gradio) because I had the same issue when i tried to use rvc webui and stable diffusion on google colab.

**Comment by SociallyIneptWeeb** [comment]
I experience that when using stable diffusion becos they shadowbanned it on Google colab. However, rvc webui on Google colab is still ok and many still use it to train voice models for hours at a time.

**Comment by SociallyIneptWeeb** [comment]
It might be due to your google account using beyond its daily limit? So maybe using a new Google account might work.

**Comment by codecooker1** [comment]
> It might be due to your google account using beyond its daily limit? So maybe using a new Google account might work.

Tried from two different account doesn't works.

Btw I'm new to this whole AI stuff is there any way to just use only the voice conversion part without anythong else from this code that works without gpu?

**Comment by SociallyIneptWeeb** [comment]
For just voice conversion, you will have to use rvc. Unfortunate you will need a GPU for it. Without one, Google colab is the only option.

**Comment by codecooker1** [comment]
Thanks. I will try searching for a way to use is as rest api like thing after my exams starting this Sunday.

**Comment by SociallyIneptWeeb** [comment]
Yup, if you are able to get the colab working, for either this or the official rvc, you can probably interact with the gradio API which should fit your project

**Comment by reggietorres** [comment]
Now im getting this issue, and im using an nvidia gpu
