### ISSUE TITLE
Issue with the webui command

### ISSUE THREAD

**Issue by ItsDarkWaffle** [SociallyIneptWeeb/AICoverGen#30]
It doesnt generate a url and i have no idea why.
```
PS C:\Users\tothr\AICoverGen\AICoverGen\AICoverGen\AICoverGen> python src/webui.py
2023-08-15 00:02:05 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
2023-08-15 00:02:05 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-08-15 00:02:05 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-08-15 00:02:05 | INFO | faiss.loader | Loading faiss.
2023-08-15 00:02:05 | INFO | faiss.loader | Successfully loaded faiss.
Traceback (most recent call last):
  File "C:\Users\tothr\AICoverGen\AICoverGen\AICoverGen\AICoverGen\src\webui.py", line 160, in <module>
    public_models = json.load(infile)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\encodings\cp1250.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x88 in position 6904: character maps to <undefined>
```

**Comment by ItsDarkWaffle** [comment]
Thank you it fixed it!

**Comment by ItsDarkWaffle** [comment]
Thank you it fixed it!
