### ISSUE TITLE
too many indices for array: array is 1-dimensional, but 2 were indexed, while local path song input

### ISSUE THREAD

**Issue by IndraTensei** [SociallyIneptWeeb/AICoverGen#31]
when tried to input song through path this error came in 
Tried changing formats as well (.wav/.mp3/.mp4)

```
2023-08-18 12:05:20 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 500 Internal Server Error"
2023-08-18 12:05:21 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"

0it [00:00, ?it/s]Traceback (most recent call last):
  File "/content/AICoverGen/src/main.py", line 247, in song_cover_pipeline
    orig_song_path, vocals_path, instrumentals_path, main_vocals_path, backup_vocals_path, main_vocals_dereverb_path = preprocess_song(song_input, mdx_model_params, song_id, is_webui, input_type, progress)
  File "/content/AICoverGen/src/main.py", line 149, in preprocess_song
    vocals_path, instrumentals_path = run_mdx(mdx_model_params, song_output_dir, os.path.join(mdxnet_models_dir, 'UVR-MDX-NET-Voc_FT.onnx'), orig_song_path, denoise=True, keep_orig=keep_orig)
  File "/content/AICoverGen/src/mdx.py", line 262, in run_mdx
    wave_processed = -(mdx_sess.process_wave(-wave, m_threads)) + (mdx_sess.process_wave(wave, m_threads))
  File "/content/AICoverGen/src/mdx.py", line 214, in process_wave
    waves = self.segment(wave, False, chunk)
  File "/content/AICoverGen/src/mdx.py", line 135, in segment
    cut = wave[:, start:end].copy()
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1392, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1097, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
  File "/content/AICoverGen/src/main.py", line 274, in song_cover_pipeline
    raise_exception(str(e), is_webui)
  File "/content/AICoverGen/src/main.py", line 76, in raise_exception
    raise gr.Error(error_msg)
gradio.exceptions.Error: 'too many indices for array: array is 1-dimensional, but 2 were indexed'
```

**Comment by SociallyIneptWeeb** [comment]
When changing formats, do you mean changing the extension of the file? Or using a different file format?

**Comment by IndraTensei** [comment]
> When changing formats, do you mean changing the extension of the file? Or using a different file format?

different file format, at the end i resorted to upload in youtube and made it unlisted.
worked like a charm

**Comment by SociallyIneptWeeb** [comment]
I'll look into this, might be an issue where the audio file is mono instead of stereo so it gives an error.

**Comment by SociallyIneptWeeb** [comment]
Yup, that was the issue. I pushed a fix, so you can pull the new changes and test the local file upload which should work now!

**Comment by IndraTensei** [comment]
> Yup, that was the issue. I pushed a fix, so you can pull the new changes and test the local file upload which should work now!
Yes its solved for me as well, Thanks a ton
