### ISSUE TITLE
No such file or directory UVR-MDX-NET-Voc_FT.onnx

### ISSUE THREAD

**Issue by TroyanosNoGracias** [SociallyIneptWeeb/AICoverGen#32]
Hello, I'm getting the following error when trying to use the program. I downloaded a youtube video in .wav format.
```

Traceback (most recent call last):
  File "C:\Users\jarur\AICoverGen\src\mdx.py", line 84, in get_hash
    with open(model_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jarur\\AICoverGen\\mdxnet_models\\UVR-MDX-NET-Voc_FT.onnx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jarur\AICoverGen\src\main.py", line 265, in song_cover_pipeline
    orig_song_path, vocals_path, instrumentals_path, main_vocals_path, backup_vocals_path, main_vocals_dereverb_path = preprocess_song(song_input, mdx_model_params, song_id, is_webui, input_type, progress)
  File "C:\Users\jarur\AICoverGen\src\main.py", line 167, in preprocess_song
    vocals_path, instrumentals_path = run_mdx(mdx_model_params, song_output_dir, os.path.join(mdxnet_models_dir, 'UVR-MDX-NET-Voc_FT.onnx'), orig_song_path, denoise=True, keep_orig=keep_orig)
  File "C:\Users\jarur\AICoverGen\src\mdx.py", line 245, in run_mdx
    model_hash = MDX.get_hash(model_path)
  File "C:\Users\jarur\AICoverGen\src\mdx.py", line 88, in get_hash
    model_hash = hashlib.md5(open(model_path, 'rb').read()).hexdigest()
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jarur\\AICoverGen\\mdxnet_models\\UVR-MDX-NET-Voc_FT.onnx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jarur\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\jarur\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1392, in process_api
    result = await self.call_function(
  File "C:\Users\jarur\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1097, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\jarur\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\jarur\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\jarur\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\jarur\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\jarur\AICoverGen\src\main.py", line 292, in song_cover_pipeline
    raise_exception(str(e), is_webui)
  File "C:\Users\jarur\AICoverGen\src\main.py", line 80, in raise_exception
    raise gr.Error(error_msg)
gradio.exceptions.Error: "[Errno 2] No such file or directory: 'C:\\\\Users\\\\jarur\\\\AICoverGen\\\\mdxnet_models\\\\UVR-MDX-NET-Voc_FT.onnx'"
```
Any help would be greatly appreciated.

**Comment by TroyanosNoGracias** [comment]
I forgot to execute python src/download_models.py before opening the UI.

Now it works proper.
