### ISSUE TITLE
[Questions] Can we add pitch/key control for the instruments?

### ISSUE THREAD

**Issue by okejadi** [SociallyIneptWeeb/AICoverGen#34]
Sometimes I feel the cover voice pitch is not matching with the instruments and I feel like to increase it, can we?

**Comment by SociallyIneptWeeb** [comment]
Usually, we adjust the cover voice pitch instead to fit the instrumentals, so as long as the pitch change for vocals is a multiple of 12, like -24, -12, 12, 24, the voice pitch will match the instrumentals. Changing the pitch of the instrumentals themselves is usually not recommended since it would sound horrible if just applying raw pitch change.

**Comment by SociallyIneptWeeb** [comment]
Ok I have added a pitch control for instruments, and though it reduces sound quality slightly, I feel like it should still be acceptable, so feel free to pull the new changes and try it out!

**Comment by okejadi** [comment]
Thankyou for working on it!

I altered the Overall Pitch Change values after I have done generating the 0 version of it, but this happened

`2023-08-28 02:31:35 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
2023-08-28 02:31:48 | INFO | fairseq.tasks.hubert_pretraining | current directory is /content/AICoverGen
2023-08-28 02:31:48 | INFO | fairseq.tasks.hubert_pretraining | HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
2023-08-28 02:31:48 | INFO | fairseq.models.hubert.hubert | HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
gin_channels: 256 self.spk_embed_dim: 109
<All keys matched successfully>
Traceback (most recent call last):
  File "/content/AICoverGen/src/main.py", line 297, in song_cover_pipeline
    instrumentals_path = pitch_shift(instrumentals_path, pitch_change_all)
  File "/content/AICoverGen/src/main.py", line 144, in pitch_shift
    y_shifted = tfm.build_array(input_array=y, sample_rate_in=sr)
  File "/usr/local/lib/python3.10/dist-packages/sox/transform.py", line 833, in build_array
    args.extend(self._input_format_args(input_format))
  File "/usr/local/lib/python3.10/dist-packages/sox/transform.py", line 193, in _input_format_args
    self._validate_input_format(input_format)
  File "/usr/local/lib/python3.10/dist-packages/sox/transform.py", line 159, in _validate_input_format
    raise ValueError(
ValueError: Invalid file_type. Must be one of []

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1392, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1097, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
  File "/content/AICoverGen/src/main.py", line 315, in song_cover_pipeline
    raise_exception(str(e), is_webui)
  File "/content/AICoverGen/src/main.py", line 83, in raise_exception
    raise gr.Error(error_msg)
gradio.exceptions.Error: 'Invalid file_type. Must be one of []'
2023-08-28 02:32:04 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 500 Internal Server Error"
2023-08-28 02:32:05 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"`

My settings
Pitch : 1
Overall Pitch Change : other than 0
Wet Level: 0.5
Other value at its default value

It just never went success unless I put 0 overall pitch change value...

**Comment by SociallyIneptWeeb** [comment]
I'm not too sure why this error is showing up haha, have you tried with other songs?

**Comment by SociallyIneptWeeb** [comment]
I believe this is a Sox error that occurs if Sox is not installed, so just ensure that you have it installed by following the instructions in the readme
