### ISSUE TITLE
invalid load key, '\x00'.

### ISSUE THREAD

**Issue by m3ll0w1** [SociallyIneptWeeb/AICoverGen#37]
Traceback (most recent call last):
  File "/content/AICoverGen/src/main.py", line 275, in song_cover_pipeline
    voice_change(voice_model, main_vocals_dereverb_path, ai_vocals_path, pitch_change, index_rate, filter_radius, rms_mix_rate, protect, is_webui)
  File "/content/AICoverGen/src/main.py", line 184, in voice_change
    cpt, version, net_g, tgt_sr, vc = get_vc(device, config.is_half, config, rvc_model_path)
  File "/content/AICoverGen/src/rvc.py", line 113, in get_vc
    cpt = torch.load(model_path, map_location='cpu')
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x00'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1392, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1097, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
  File "/content/AICoverGen/src/main.py", line 293, in song_cover_pipeline
    raise_exception(str(e), is_webui)
  File "/content/AICoverGen/src/main.py", line 81, in raise_exception
    raise gr.Error(error_msg)
gradio.exceptions.Error: "invalid load key, '\\x00'."

**Comment by m3ll0w1** [comment]
I use the website version since it doesn't need to run gpu.

**Comment by SociallyIneptWeeb** [comment]
I believe this is an issue with the format of the voice model. Can you ensure it is a rvc v2 trained model? Instead of rvc v1/sovits for example

**Comment by m3ll0w1** [comment]
yes i am pretty sure it is (RVC v2 500 epochs)

**Comment by SociallyIneptWeeb** [comment]
Could you provide the download link to the model?

**Comment by m3ll0w1** [comment]
https://huggingface.co/leeloli/wonyoung-by-leelo/resolve/main/wonyoung.zip

**Comment by SociallyIneptWeeb** [comment]
There seems to be extra .pth and .index files in the zip, which caused download process to not extract the correct voice model and index file. I will fix it and let you know when I made the changes

**Comment by SociallyIneptWeeb** [comment]
Ok I fixed it, could you rerun your colab notebook and test it out again? Thanks!

**Comment by m3ll0w1** [comment]
hey man just letting you that a temporary fix for this is to locally upload those models in the upload model.

**Comment by m3ll0w1** [comment]
thanks! man

**Comment by m3ll0w1** [comment]
i think the problem is the rvc model itself i tried it for the others, it works pretty well.

**Comment by SociallyIneptWeeb** [comment]
I tested with the model using the link you provided and it should work for that as well with the new changes, the zip was an outlier that had multiple model and index files that were empty

**Comment by m3ll0w1** [comment]
yeah it is fixed i just forgot to restart my runtime xD thanks for the fix!
