### ISSUE TITLE
error - index -1 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by lokipoki122** [SociallyIneptWeeb/AICoverGen#43]
everything was working fine but suddenly its coming like this and i even tried by removing everything and again installed but still the same
![Capture](https://github.com/SociallyIneptWeeb/AICoverGen/assets/117144751/c81f43c6-3f99-47d1-afe6-fedf90981d74)
![Capture 2](https://github.com/SociallyIneptWeeb/AICoverGen/assets/117144751/2c9ff465-126a-4e2b-9850-d360d0aa949b)

**Comment by SociallyIneptWeeb** [comment]
Can you send the image of the full error trace log? Including the one before this.

**Comment by lokipoki122** [comment]
![Capture 1](https://github.com/SociallyIneptWeeb/AICoverGen/assets/117144751/a96f0b26-da72-4adb-ac5d-cfb6d208000d)

**Comment by SociallyIneptWeeb** [comment]
It seems to be an issue with the format of the rvc model. Is it RVC V2?

**Comment by lokipoki122** [comment]
i reinstalled and now its working fine .. thanks a lot

**Comment by lokipoki122** [comment]
might be something fixed with my reinstall or gradio was down yerterday but somehow it is fixed thanks a bunch

**Comment by marekk-gh** [comment]
im having the same issue. the model is rvc v2, as it has the tag in the ai hub discord. i already tried reinstalling the app and the model.

Logs:
```
Traceback (most recent call last):
  File "C:\AICoverGen\src\main.py", line 291, in song_cover_pipeline
    voice_change(voice_model, main_vocals_dereverb_path, ai_vocals_path, pitch_change, f0_method, index_rate, filter_radius, rms_mix_rate, protect, crepe_hop_length, is_webui)
  File "C:\AICoverGen\src\main.py", line 201, in voice_change
    rvc_infer(rvc_index_path, index_rate, vocals_path, output_path, pitch_change, f0_method, cpt, version, net_g, filter_radius, tgt_sr, rms_mix_rate, protect, crepe_hop_length, vc, hubert_model)
  File "C:\AICoverGen\src\rvc.py", line 150, in rvc_infer
    audio_opt = vc.pipeline(hubert_model, net_g, 0, audio, input_path, times, pitch_change, f0_method, index_path, index_rate, if_f0, filter_radius, tgt_sr, 0, rms_mix_rate, version, protect, crepe_hop_length)
  File "C:\AICoverGen\src\vc_infer_pipeline.py", line 571, in pipeline
    self.vc(
  File "C:\AICoverGen\src\vc_infer_pipeline.py", line 424, in vc
    npy = np.sum(big_npy[ix] * np.expand_dims(weight, axis=2), axis=1)
IndexError: index -1 is out of bounds for axis 0 with size 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\blocks.py", line 1392, in process_api
    result = await self.call_function(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\blocks.py", line 1097, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
  File "C:\AICoverGen\src\main.py", line 316, in song_cover_pipeline
    raise_exception(str(e), is_webui)
  File "C:\AICoverGen\src\main.py", line 83, in raise_exception
    raise gr.Error(error_msg)
gradio.exceptions.Error: 'index -1 is out of bounds for axis 0 with size 0'
```

**Comment by mateuszkochanek** [comment]
@marekknet Did you manage to fix this? I have the same problem. I didn't really reinstall - as I am forking this repository too add something, but my model trained on my voice does not work. Other models work correctly.
