### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by shimizu-izumi** [SociallyIneptWeeb/AICoverGen#6]
Additional notes: I use a python venv
OS: Windows 11
```
16 series/10 series P40 forced single precision
Traceback (most recent call last):
  File "D:\Programme\AICoverGen\src\main.py", line 189, in <module>
    cover_path = song_cover_pipeline(args.youtube_link, rvc_dirname, args.pitch_change)
  File "D:\Programme\AICoverGen\src\main.py", line 161, in song_cover_pipeline
    ai_vocals_path = voice_change(voice_model, main_vocals_dereverb_path, pitch_change)
  File "D:\Programme\AICoverGen\src\main.py", line 98, in voice_change
    config = Config(device, is_half)
  File "D:\Programme\AICoverGen\src\rvc.py", line 24, in __init__
    self.x_pad, self.x_query, self.x_center, self.x_max = self.device_config()
  File "D:\Programme\AICoverGen\src\rvc.py", line 44, in device_config
    with open("trainset_preprocess_pipeline_print.py", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'trainset_preprocess_pipeline_print.py'
```

**Comment by SociallyIneptWeeb** [comment]
This should be fixed with the new commit. Pull the new changes from github and you can test it again.
