### ISSUE TITLE
Input and weight type error

### ISSUE THREAD

**Issue by shimizu-izumi** [SociallyIneptWeeb/AICoverGen#8]
OS: Windows 11
Additional info: I use a Python VENV
```
<All keys matched successfully>
Traceback (most recent call last):
  File "D:\Programme\AICoverGen\src\main.py", line 192, in <module>
    cover_path = song_cover_pipeline(args.youtube_link, rvc_dirname, args.pitch_change)
  File "D:\Programme\AICoverGen\src\main.py", line 164, in song_cover_pipeline
    ai_vocals_path = voice_change(voice_model, main_vocals_dereverb_path, pitch_change)
  File "D:\Programme\AICoverGen\src\main.py", line 104, in voice_change
    rvc_infer(rvc_index_path, vocals_path, output_path, pitch_change, cpt, version, net_g, tgt_sr, vc, hubert_model)
  File "D:\Programme\AICoverGen\src\rvc.py", line 147, in rvc_infer
    audio_opt = vc.pipeline(hubert_model, net_g, 0, audio, input_path, times, pitch_change, 'crepe', index_path, 0.7, if_f0, 3, tgt_sr, 0, 0.25, version, 0.33, f0_file=None)
  File "D:\Programme\AICoverGen\src\vc_infer_pipeline.py", line 347, in pipeline
    self.vc(
  File "D:\Programme\AICoverGen\src\vc_infer_pipeline.py", line 185, in vc
    logits = model.extract_features(**inputs)
  File "D:\Programme\AICoverGen\venv\lib\site-packages\fairseq\models\hubert\hubert.py", line 535, in extract_features
    res = self.forward(
  File "D:\Programme\AICoverGen\venv\lib\site-packages\fairseq\models\hubert\hubert.py", line 437, in forward
    features = self.forward_features(source)
  File "D:\Programme\AICoverGen\venv\lib\site-packages\fairseq\models\hubert\hubert.py", line 392, in forward_features
    features = self.feature_extractor(source)
  File "D:\Programme\AICoverGen\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Programme\AICoverGen\venv\lib\site-packages\fairseq\models\wav2vec\wav2vec2.py", line 895, in forward
    x = conv(x)
  File "D:\Programme\AICoverGen\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Programme\AICoverGen\venv\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "D:\Programme\AICoverGen\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Programme\AICoverGen\venv\lib\site-packages\torch\nn\modules\conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\Programme\AICoverGen\venv\lib\site-packages\torch\nn\modules\conv.py", line 309, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same
```

**Comment by SociallyIneptWeeb** [comment]
Is the rvc model you're using trained using RVC V2?

**Comment by shimizu-izumi** [comment]
I got it from the AI HUB Discord and it is tagged with RVC v2

**Comment by SociallyIneptWeeb** [comment]
What's GPU are you using?

**Comment by shimizu-izumi** [comment]
GTX 1070 (Palit dual version)

**Comment by SociallyIneptWeeb** [comment]
I have made some fixes, so could you try pulling those and testing the program again?

**Comment by shimizu-izumi** [comment]
Now its stuck on ``<All keys matched successfully>``

**Comment by SociallyIneptWeeb** [comment]
Yah it takes time for the rvc voice change to run

**Comment by SociallyIneptWeeb** [comment]
As I have a 3060, it only takes less than a minute. For a 1070, it might take more than a minute

**Comment by shimizu-izumi** [comment]
It is there for 10 minutes now with a about 1 minute and and 20 seconds clip sound like it's stuck to me, espically when considiring that another RVC based software that I used before that can also be used as a realtime voice changer and a clip of the same length took about 1 minute to process

**Comment by SociallyIneptWeeb** [comment]
Hmm yah that shouldn't take THAT long. Can you check if the program is using your gpu when it reaches the `all keys matched successfully part`? Like open task manager and monitor the gpu memory usage.

**Comment by shimizu-izumi** [comment]
It is using my GPU, but instead of constantly using it it's more like 0% - 91% - 0% - 91% and that switches every second

**Comment by shimizu-izumi** [comment]
I can do that, and I will also try running it using the WSL

**Comment by shimizu-izumi** [comment]
Ah, it's done it just takes ages for some reason

**Comment by SociallyIneptWeeb** [comment]
Lol did it take more than 10 minutes?

**Comment by shimizu-izumi** [comment]
I will stop the time on the next run, but I would say the reason why it's so slow is because it switches between 0% and 90%

**Comment by shimizu-izumi** [comment]
uhh I just noticed the output file is 9 minutes for some reason

**Comment by shimizu-izumi** [comment]
It took 3 minutes from start to finish with an input file of 2 Minutes and 22 Seconds

**Comment by SociallyIneptWeeb** [comment]
Is the YouTube video from a playlist perhaps? For the output file of 9 minutes

**Comment by SociallyIneptWeeb** [comment]
> It took 3 minutes from start to finish with an input file of 2 Minutes and 22 Seconds

This seems about right

**Comment by shimizu-izumi** [comment]
> Is the YouTube video from a playlist perhaps? For the output file of 9 minutes

No

**Comment by SociallyIneptWeeb** [comment]
Do subsequent generations have this issue?
