### ISSUE TITLE
Problem with Running WebUI

### ISSUE THREAD

**Issue by gargoylefad** [SociallyIneptWeeb/AICoverGen#82]
Timer: 00:01:37Traceback (most recent call last):
  File "/content/HRVC/HRVC/src/webui.py", line 8, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

![image](https://github.com/SociallyIneptWeeb/AICoverGen/assets/140941810/d5eb89aa-2677-4920-b97f-4b1809760dce)

**Comment by TAyanoA** [comment]
> Timer: 00:01:37Traceback (most recent call last): File "/content/HRVC/HRVC/src/webui.py", line 8, in import gradio as gr ModuleNotFoundError: No module named 'gradio'
> 
> ![image](https://user-images.githubusercontent.com/140941810/281985589-d5eb89aa-2677-4920-b97f-4b1809760dce.png)

I am also facing the same issue as you. The 'Install requirements' section has some errors.
![unknown_2023 11 10-09 02](https://github.com/SociallyIneptWeeb/AICoverGen/assets/150425657/78487b3f-26f2-4f13-bb0f-9a8d78cdaf48)

**Comment by binibin1111** [comment]
I am also facing the same issue as you

**Comment by ViperPsychoIT** [comment]
The gradio module is missing, install it via pip install gradio==3.39.0

> Timer: 00:01:37Traceback (most recent call last): File "/content/HRVC/HRVC/src/webui.py", line 8, in import gradio as gr ModuleNotFoundError: No module named 'gradio'
> 
> ![image](https://user-images.githubusercontent.com/140941810/281985589-d5eb89aa-2677-4920-b97f-4b1809760dce.png)

**Comment by oibert12345** [comment]
I tried installing gradio and it now says there's no module called sox

**Comment by ArtificialPistol** [comment]
Replace everything under Install Requirements to this: 

#@title Install requirements
!pip install -q -r requirements.txt
clear_output()
!pip install gradio==3.39.0
clear_output()
!pip install sox
clear_output()
!pip install yt_dlp
clear_output()
!pip install pedalboard
clear_output()
!pip install onnxruntime
clear_output()
!pip install fairseq
clear_output()
!pip install ffmpeg
clear_output()
!pip install faiss-cpu
!pip install faiss-gpu
clear_output() 
!pip install praat-parselmouth
clear_output()
!pip install pyworld
clear_output()
!pip install torchcrepe
clear_output()
print("Finished Installing Requirements")
!sudo apt update
clear_output()
print("Finished Updating")
!sudo apt install sox
clear_output()
print("Finished running this cell, proceed to the next cell")

**Comment by oibert12345** [comment]
omg this worked, tysm!

**Comment by TAyanoA** [comment]
> Replace everything under Install Requirements to this:
> 
> #@title Install requirements !pip install -q -r requirements.txt clear_output() !pip install gradio==3.39.0 clear_output() !pip install sox clear_output() !pip install yt_dlp clear_output() !pip install pedalboard clear_output() !pip install onnxruntime clear_output() !pip install fairseq clear_output() !pip install ffmpeg-python clear_output() !pip install faiss-cpu !pip install faiss-gpu clear_output() !pip install praat-parselmouth clear_output() !pip install pyworld clear_output() !pip install torchcrepe clear_output() print("Finished Installing Requirements") !sudo apt update clear_output() print("Finished Updating") !sudo apt install sox clear_output() print("Finished running this cell, proceed to the next cell")
> 
> then do the Runtime/Run All thing again

This installation has drop-out issues. Generating a file on the WebUI website gets stuck at 'Separating From Vocal to Instrumental'.
![unknown_2023 11 13-06 34](https://github.com/SociallyIneptWeeb/AICoverGen/assets/150425657/52291b95-1d9d-4ef9-b40b-4157953fccd2)
