### ISSUE TITLE
ConnectionResetError

### ISSUE THREAD

**Issue by Pleb6381** [SociallyIneptWeeb/AICoverGen#89]
All keys matched successfully>
Initiating prediction with a crepe_hop_length of: 128
2023-12-06 22:25:13 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
2023-12-06 22:25:13 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
2023-12-06 22:25:13 | ERROR | asyncio | Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\Wesley\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Wesley\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

I get this error every time I make an AI cover and it seems to be related to poor generation

**Comment by JackismyShephard** [comment]
I am getting this error as well but audio generation seems to work though. Did you ever solve this problem?

**Comment by JackismyShephard** [comment]
@Pleb6381 I have solved this error at my fork of this repo at : https://github.com/JackismyShephard/ultimate-rvc
