### ISSUE TITLE
WinError2 when i tried to generete a cover

### ISSUE THREAD

**Issue by system3600** [SociallyIneptWeeb/AICoverGen#91]
Traceback (most recent call last):
  File "C:\Users\Micro\Desktop\IAvoz\AICoverGen\src\my_utils.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "C:\Users\Micro\AppData\Local\Programs\Python\Python310\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "C:\Users\Micro\AppData\Local\Programs\Python\Python310\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "C:\Users\Micro\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Micro\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] O sistema não pode encontrar o arquivo especificado

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Micro\Desktop\IAvoz\AICoverGen\src\main.py", line 291, in song_cover_pipeline
    voice_change(voice_model, main_vocals_dereverb_path, ai_vocals_path, pitch_change, f0_method, index_rate, filter_radius, rms_mix_rate, protect, crepe_hop_length, is_webui)
  File "C:\Users\Micro\Desktop\IAvoz\AICoverGen\src\main.py", line 201, in voice_change
    rvc_infer(rvc_index_path, index_rate, vocals_path, output_path, pitch_change, f0_method, cpt, version, net_g, filter_radius, tgt_sr, rms_mix_rate, protect, crepe_hop_length, vc, hubert_model)
  File "C:\Users\Micro\Desktop\IAvoz\AICoverGen\src\rvc.py", line 147, in rvc_infer
    audio = load_audio(input_path, 16000)
  File "C:\Users\Micro\Desktop\IAvoz\AICoverGen\src\my_utils.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: [WinError 2] O sistema não pode encontrar o arquivo especificado

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Micro\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Micro\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1392, in process_api
    result = await self.call_function(
  File "C:\Users\Micro\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1097, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Micro\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Micro\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Micro\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\Micro\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\Micro\Desktop\IAvoz\AICoverGen\src\main.py", line 316, in song_cover_pipeline
    raise_exception(str(e), is_webui)
  File "C:\Users\Micro\Desktop\IAvoz\AICoverGen\src\main.py", line 83, in raise_exception
    raise gr.Error(error_msg)
gradio.exceptions.Error: 'Failed to load audio: [WinError 2] O sistema não pode encontrar o arquivo especificado'

**Comment by Synaelle** [comment]
Same here 🤷‍♀️
Tried many things, the same error everytime.
